import {StyleSheet, Dimensions} from 'react-native';
import {
  backgroundColor,
  shadowColor,
} from 'react-native/Libraries/Components/View/ReactNativeStyleAttributes';
const width = Dimensions.get('window').width;
module.exports = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  header: {
    flex: 1,
  },
  actualText: {
    fontSize: 24,
    paddingTop: 50,
    paddingLeft: 27,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  footertext1: {
    fontSize: 16,
    paddingTop: 35,
    paddingLeft: 48,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  image: {
    flex: 1,
    justifyContent: 'center',
  },
  mainLogo: {
    marginTop: -20,
    justifyContent: 'center',
    alignItems: 'center',
  },

  loginRocket: {
    marginTop: 90,
    justifyContent: 'center',
    alignItems: 'center',
  },
  mainTextStyle: {
    // paddingHorizontal: 100,
    paddingTop: 0,
    fontSize: 30,
    textAlign: 'center',
    // fontFamily: "verdana",
    fontWeight: 'bold',
    color: '#212121',
  },
  loginDescription: {
    // paddingHorizontal: 100,
    marginTop: 15,
    fontSize: 12,
    textAlign: 'center',
    // fontFamily: "verdana",
    color: '#737373',
  },
  footer: {
    flex: 1.5,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    backgroundColor: '#1D1D1D',
  },
  signinbutton: {
    backgroundColor: '#73C3FE',
    borderRadius: 55,
    marginTop: 35,
    marginHorizontal: 90,
    padding: 15,
    justifyContent: 'center',
    alignItems: 'center',
  },
  buttontext: {
    fontSize: 16,
    fontWeight: 'bold',
    color: 'black',
  },
  textbox: {
    marginTop: 25,
    marginHorizontal: 40,
  },
  textboxtext: {
    backgroundColor: 'rgba(255, 255, 255, 0.23)',
    borderRadius: 50,
    padding: 8,
    color: '#FFFFFF',
    paddingLeft: 30,
    margin: 10,
  },
  img: {
    paddingTop: 25,
    paddingHorizontal: 21,
  },
  hometext: {
    fontSize: 28,
    paddingTop: 41,
    paddingLeft: 21,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  pumptext: {
    fontSize: 28,
    paddingTop: 25,
    paddingLeft: 21,
    fontWeight: 'bold',
    color: '#ffffff',
  },
  statusview: {
    width: width - 43,
    height: 120,
    backgroundColor: 'rgba(114,196,254,0.57)',
    borderRadius: 18,
    marginLeft: 21,
    marginTop: 18,
  },
  devices: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    // flex: 1,
    // justifyContent: 'space-between'
  },
  R: {
    height: 30,
    width: 30,
    borderRadius: 100,
    backgroundColor: '#FF022C',
  },
  Y: {
    height: 30,
    width: 30,
    borderRadius: 100,
    backgroundColor: '#E3E300',
  },
  B: {
    height: 30,
    width: 30,
    borderRadius: 100,
    backgroundColor: '#44B5FF',
  },
  R_shadow: {
    margin: 30,
    marginLeft: 80,
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginRight: 80,
    justifyContent: 'space-around',
  },
  main_off: {
    height: 165,
    width: 165,
    borderRadius: 100,
    backgroundColor: 'rgba(130, 130, 127, 0.5)',
    marginLeft: 90,
    marginTop: 60,
  },
  main_on: {
    height: 165,
    width: 165,
    borderRadius: 100,
    backgroundColor: 'rgba(2, 228, 116, 0.55)',
    marginLeft: 90,
    marginTop: 60,
  },
  deviceon: {
    width: 130,
    height: 130,
    backgroundColor: 'rgba(2, 228, 116, 0.55)',
    borderRadius: 18,
    margin: 25,
    marginBottom: 10,
  },
  pumpoff: {
    width: 130,
    height: 130,
    backgroundColor: '#464444',
    borderRadius: 18,
    margin: 25,
    marginBottom: 10,
  },
  pumpon: {
    width: 130,
    height: 130,
    backgroundColor: 'rgba(2, 228, 116, 0.55)',
    borderRadius: 18,
    margin: 25,
    marginBottom: 10,
  },
  deviceoff: {
    width: 130,
    height: 130,
    backgroundColor: '#464444',
    borderRadius: 18,
    margin: 25,
    marginBottom: 10,
  },
  chartbox: {
    borderRadius: 10,
    paddingRight: 10,
    marginLeft: 10,
    // backgroundColor:"red"
  },
  input: {
    height: 40,
    width: 40,
    borderRadius: 8,
    margin: 5,
    fontSize: 18,
    borderWidth: 1,
    padding: 10,
    paddingLeft: 14,
  },

  dropdown: {
    height: 24,
    marginTop: 10,
    borderColor: 'gray',
    borderWidth: 1,
    borderRadius: 5,
    paddingHorizontal: 8,
  },
  icon: {
    marginRight: 5,
  },
  placeholderStyle: {
    fontSize: 14,
  },
  selectedTextStyle: {
    fontSize: 14,
  },
  iconStyle: {
    width: 20,
    height: 20,
  },
  inputSearchStyle: {
    height: 40,
    fontSize: 16,
  },

  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 22,
  },
  modalView: {
    margin: 20,
    backgroundColor: 'white',
    borderRadius: 20,
    padding: 35,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
  },
  button: {
    borderRadius: 20,
    padding: 10,
    elevation: 2,
  },
  buttonOpen: {
    backgroundColor: '#F194FF',
  },
  buttonClose: {
    backgroundColor: '#2196F3',
  },
  textStyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
  },
  modalText: {
    marginBottom: 15,
    textAlign: 'center',
  },
  fabButton: {
    position: 'absolute',
    bottom: 25,
    right: 20,
    backgroundColor: '#bae6fd',
    width: 60,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 8,
  },
  fabButtonDisabled: {
    position: 'absolute',
    bottom: 25,
    right: 20,
    backgroundColor: '#a3a3a3',
    width: 60,
    height: 40,
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    borderRadius: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    backgroundColor: 'white',
    padding: 20,
    paddingTop: 10,
    margin: 20,
    borderRadius: 10,
    elevation: 5,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 10,
  },
  title: {
    fontSize: 16,
  },
  closeButton: {
    padding: 5,
  },
  button: {
    backgroundColor: '#007AFF',
    paddingVertical: 10,
    borderRadius: 5,
    marginTop: 20,
  },
  buttonText: {
    color: 'white',
    textAlign: 'center',
  },

  selectText: {
    fontSize: 14,
    marginBottom: 20,
  },
  colorContainer: {
    alignItems: 'center',
  },

  colorPicker: {
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
  },
  colorCircle: {
    width: 25,
    height: 25,
    borderRadius: 25,
    margin: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectedColorContainer: {
    marginTop: 20,
    alignItems: 'center',
  },
  selectedColorText: {
    fontSize: 18,
    marginBottom: 10,
  },
  selectedColor: {
    width: 50,
    height: 50,
    borderRadius: 25,
    marginTop: 5,
  },
});
